### ISSUE TITLE
Broken in Django 1.10

### ISSUE THREAD

**Issue by chrisspen** [caioariede/django-input-mask#9]
This no longer seems to work in Django 1.10.

Any page using it throws the Javascript error `Uncaught TypeError: c.split is not a function` coming from `jquery.maskedinput.min.js:7`.

**Comment by marcoshemann** [comment]
Try subst c.split to c.toString().split
